#!/usr/bin/env python3

import time, configparser as cp
from apps.xoraCams.cams.topCam import topCam
from apps.shared.core.datatypes import *

# -- -- -- --
ini_file: str = "conf/xorai.ini"
XORA_INI: cp.ConfigParser = cp.ConfigParser()
if len(XORA_INI.read(ini_file)) != 0:
   raise FileNotFoundError(ini_file)
# -- -- -- --
TOP_CAM: topCam = topCam(XORA_INI[""])
MAIN_TICK_SLEEP: float = 8.0

def init():
   TOP_CAM.start()

def main():
   # -- init code --
   init()
   # -- man tick --
   def __main_tick() -> tickCode:
      print("[ run_cams: main_tick ]")
      return tickCode.OK
   # -- main loop --
   while True:
      tick_code: tickCode = __main_tick()
      time.sleep(MAIN_TICK_SLEEP)


# -- -- -- entry point -- -- --
if __name__ == "__main__":
   print("\n\t-- [ main ] --\n")
   main()
