#!/usr/bin/sh


RUN_XOR_AI="/run/xora.ai"


if [ "$(id -u)" -ne 0 ]; then
  echo "script must be run as root"
  exit 1
fi

if [ ! -f $RUN_XOR_AI ]; then
  echo "PATH_NOT_FOUND: $RUN_XOR_AI"
  # make root in run folder
  mkdir "$RUN_XOR_AI"
fi

chown xora:xora -R /run/xora.ai

# link ramdisk back to the app
cd /opt/xortana.ai || exit 1
ln -s /run/xora.ai/ ramdsk
