#!/usr/bin/env python3

import time
import setproctitle
# -- system --
from shared.sysCamMngr import sysCamMngr


APP_NAME = "xora-ai/cams"

camMngr: sysCamMngr = sysCamMngr()
camMngr.sky_cam.start_cam_thread()


# -- -- -- entry point -- -- --
if __name__ == "__main__":
   setproctitle.setproctitle(APP_NAME)
   while True:
      print("run_xora_cams_main_loop")
      time.sleep(8.0)
