#!/usr/bin/env python3

import time
import setproctitle


APP_NAME: str = "xor/xora"


def main():
   while True:
      print("main_loop")
      time.sleep(4.0)


# -- -- -- -- [ entry point ] -- -- -- --
if __name__ == "__main__":
    setproctitle.setproctitle(APP_NAME)
    main()
