#!/usr/bin/env python3

import time
import setproctitle
# -- system --
from shared.sysCamMngr import sysCamMngr


APP_NAME = "xora.ai/cams"

camMngr: sysCamMngr = sysCamMngr()
camMngr.sky_cam.start_cam_threads()


# -- -- -- entry point -- -- --
if __name__ == "__main__":
   setproctitle.setproctitle(APP_NAME)
   while True:
      msg = f"run_xora_cams_main_loop\n\timg_cnt: {camMngr.sky_cam.img_cnt}"
      print(msg)
      time.sleep(8.0)
