#!/usr/bin/env python3

import time, setproctitle
from shared.sysThermals import sysThermals


APP_NAME: str = "xora.ai/therm"
SYS_THERMALS: sysThermals = sysThermals()
SYS_THERMALS.init()


def main():
   while True:
      print("[ thermals main loop ]")
      time.sleep(4.0)


# -- -- [ entry point ] -- --
if __name__ == "__main__":
   setproctitle.setproctitle(APP_NAME)
   main()
