#!/usr/bin/env python3

import time
from shared.sysThermals import sysThermals


SYS_THERMALS: sysThermals = sysThermals()
SYS_THERMALS.init()


def main():
   while True:
      print("[ thermals main loop ]")
      time.sleep(4.0)


# -- -- [ entry point ] -- --
if __name__ == "__main__":
   main()
