#!/usr/bin/sh


# -- -- [ run thermals ] -- --
# XORA_CAMS="xora.ai/therm"
# sleep 2
# if [ "$(pgrep -c -x $XORA_CAMS)" != 1 ]; then
#   ps -A | grep $XORA_CAMS
#   killall -s KILL $XORA_CAMS
# fi

# -- -- [ run cams ] -- --
sleep 2
./run_cams >> /dev/null &


# -- -- [ run webui ] -- --
sleep 2
./run_webui >> /dev/null &

# -- -- [ run thermals ] -- --
sleep 20
./run_therm >> /dev/null &
