#!/usr/bin/env python3

import sys, configparser as _cp
import time
from multiprocessing import Process
from botCore.botCreator import botCreator
from sensorCore.sensorInterface import sensorInterface as _iS
from sysCore.iniLoader import load_inis
from sysCore.redOps import redOps
from sysCore.sysOps import sysOps


# -- load needed inis --
INI_BOTS, RED_OPS, SYS_OPS = load_inis()
# -- cast --
INI_BOTS: _cp.ConfigParser = INI_BOTS
RED_OPS: redOps = RED_OPS
SYS_OPS: sysOps = SYS_OPS


def main():
   print("\n\t[ -- main -- ]\n")
   botCrt: botCreator = botCreator(INI_BOTS)
   helmet_sensors: [_iS] = botCrt.create("HELMET_SENSORS")
   [print(i) for i in helmet_sensors]
   # -- start helmet sensors --
   for iS in helmet_sensors:
      iS: _iS = iS
      iS.init(SYS_OPS, RED_OPS)
      iS.start()
   # -- start cam(s) --
   cam_sensors: [] = botCrt.create("HELMET_CAMS")
   [print(i) for i in cam_sensors]
   # -- run main loop --
   while True:
      print("-- main loop --")
      time.sleep(2.0)
   # -- -- -- --


# -- entry point --
if __name__ == '__main__':
    main()
